<%@ Page Title="" Language="C#" MasterPageFile="~/Lidiflu.Master" AutoEventWireup="true" CodeFile="ShoppingCart.aspx.cs" Inherits="ShoppingCart" %>
 <%@ MasterType VirtualPath="~/Lidiflu.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="title" class="container_12">
        <h1>
            Shopping Cart</h1>
    </div>
    <div id="cartcontainer" runat="server" class="grid_9 alpha">
        <asp:GridView ID="GridView1" Width="100%" AutoGenerateColumns="False" OnRowDeleting="GridView1_RowDeleting"
            runat="server" RowStyle-VerticalAlign="Top" 
            AutoGenerateDeleteButton="True" RowStyle-HorizontalAlign="Left"
            CellPadding="5" BorderStyle="Dotted" BorderWidth="0px" Font-Size="8pt" Font-Names="Verdana"
            ForeColor="#333333" onrowcommand="GridView1_RowCommand">
            <HeaderStyle HorizontalAlign="Left" />
            <RowStyle BorderStyle="Dotted" BorderWidth="1px" Font-Names="Verdana" Font-Size="11px" />
            <Columns>
                <asp:TemplateField ControlStyle-Width="140" HeaderText="Item" SortExpression="ProdImage">
                    <ItemTemplate>
                        <asp:Image ID="Image1" runat="server" ImageUrl='<%#Bind("ProdImage") %>' />
                    </ItemTemplate>
                    <ControlStyle Width="140px"></ControlStyle>
                </asp:TemplateField>
                <asp:TemplateField ControlStyle-Width="220" HeaderText="Description" SortExpression="Description">
                    <ItemTemplate>
                        <asp:Label ID="lblDescript" runat="server" Text='<%#Bind("Description") %>' />
                    </ItemTemplate>
                    <ControlStyle Width="220px"></ControlStyle>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Price" ControlStyle-Width="60" SortExpression="Price">
                    <ItemTemplate>
                        <asp:Label ID="lblPrice" runat="server" Text='<%#Bind("Price") %>' />                       
                    </ItemTemplate>
                    <ControlStyle Width="60px"></ControlStyle>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Qty" ControlStyle-Width="80" SortExpression="Price">
                    <ItemTemplate>
                     <asp:Button ID="btnMinus" runat="server" CommandName="RemoveItem" CommandArgument="<%# ((GridViewRow) Container).RowIndex %>"
                            Text="-" />
                        <asp:Textbox ReadOnly="true" min="0" Width="20px" Height="20px" ID="txtQty" runat="server" Text='<%#Bind("Qty") %>' />
                             <asp:Button ID="btnPlus" runat="server" CommandName="AddItem" CommandArgument="<%# ((GridViewRow) Container).RowIndex %>"
                            Text="+" />
                    </ItemTemplate>
                    <ControlStyle Width="80px"></ControlStyle>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Total" ControlStyle-Width="120" ItemStyle-HorizontalAlign="Right"
                    SortExpression="Total">
                    <ItemTemplate>
                        <asp:Label ID="lblTotal" runat="server" Text='<%#Bind("Total") %>' />
                    </ItemTemplate>
                    <ControlStyle Width="120px"></ControlStyle>
                    <ItemStyle HorizontalAlign="Right"></ItemStyle>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <div id="proceed" class="grid_3 prefix_6 alpha">
            </br></br>
            <asp:DropDownList ID="drpPostage" runat="server" Width="166px" AutoPostBack="True"
                OnSelectedIndexChanged="drpPostage_SelectedIndexChanged">
                <asp:ListItem Selected="True" Value="35">U.K Delivery £35.00 </asp:ListItem>
                <asp:ListItem Value="85">Overseas Delivery £85.00</asp:ListItem>
            </asp:DropDownList>
            </br></br>
            <asp:Table ID="Table1" runat="server" Height="53px" Width="166px">
                <asp:TableRow>
                    <asp:TableCell><p>Sub Total</p></asp:TableCell>
                    <asp:TableCell ID="cellSub"></asp:TableCell>
                </asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell><p>Total</p></asp:TableCell>
                    <asp:TableCell ID="cellTotal"></asp:TableCell>
                </asp:TableRow>
            </asp:Table>
            <asp:Button ID="btnConfirm" runat="server" CssClass="btnAddToCart" Text="Place Order"
                OnClick="btnConfirm_Click" />
        </div>
    </div>
    <div id="cartside" class="grid_3 omega">
        <h2>
            Need Help</h2>
        <p class="grey-text">
            Office Hours:</br>Mon-Fri 9.30am-6.00pm</p>
        <p>
        </p>
        <p>
            +44 (0) 1313 123 1235</p>
        <p>
        </p>
        <p>
            <a style="color: #2583B7" href="mailto:enquiries@lidiflu.com">enquiries@lidiflu.com</a></p>
        <h2>
            We Accept</h2>
        <img src="Images/paymentsmall.png" />
        <h2>
            Delivery</h2>
        <p>
            We ship with UPS and a Special delivery service from Royal mail.</p>
        <p>
            </br></p>
        <p>
            UK ORDERS We aim to get all orders placed before 3pm out to you for a next day delivery.
        </p>
        <h2>
            Returns</h2>
        <p>
            <a href="#">Returns and Delivery >> </a>
        </p>
    </div>
</asp:Content>
